[package]
name = "gpui-terminal"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Terminal emulator component for gpui"
repository = "https://github.com/zortax/gpui-terminal"
authors = ["Leonard Seibold <git[@]zrtx.de"]

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed" }
gpui_platform = { git = "https://github.com/zed-industries/zed" }
alacritty_terminal = "0.26.0"
anyhow = "1.0.102"
portable-pty = "0.9.0"
ropey = "1.6.1"
parking_lot = "0.12.5"
flume = "0.12.0"

[dependencies.arboard]
version = "3.6.1"
features = ["wayland-data-control"]
